// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainWise.Core.Infrastructure.Data.Context;

#nullable disable

namespace TrainWise.Core.Migrations
{
    [DbContext(typeof(WorkoutDbContext))]
    [Migration("20260209131514_MakeMediaFieldsNullable")]
    partial class MakeMediaFieldsNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.UsersComponets.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.UsersComponets.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvailableEquipment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PreferredSessionDuration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingDaysPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutAnalysis.AiRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsApplied")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkoutPlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("AIRecommendations");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutAnalysis.PerformanceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageRPE")
                        .HasColumnType("REAL");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastWorkoutDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalSets")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalVolume")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId");

                    b.ToTable("PerformanceSnapshots");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutAnalysis.ProgressAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressStatus")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StrengthChangePercent")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VolumeChangePercent")
                        .HasColumnType("REAL");

                    b.Property<int>("WeeksStagnant")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId");

                    b.ToTable("ProgressAnalyses");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutAnalysis.VolumeAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageIntensity")
                        .HasColumnType("REAL");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSets")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalVolume")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutsCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VolumeAnalyses");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutComponents.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrimaryMuscleGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondaryMuscles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutComponents.SetExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RPE")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutTemplateExerciseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId");

                    b.HasIndex("WorkoutTemplateExerciseId");

                    b.ToTable("SetExecutions");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SplitType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetMuscleGroups")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("WorkoutTemplates");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutTemplateExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RestTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetRepsMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetRepsMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetSets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("WorkoutTemplateExercises");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.UsersComponets.UserPreferences", b =>
                {
                    b.HasOne("TrainWise.Core.Domain.Entities.UsersComponets.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("TrainWise.Core.Domain.Entities.UsersComponets.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutAnalysis.AiRecommendation", b =>
                {
                    b.HasOne("TrainWise.Core.Domain.Entities.WorkoutComponents.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId");

                    b.HasOne("TrainWise.Core.Domain.Entities.UsersComponets.User", "User")
                        .WithMany("AIRecommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutPlan", "WorkoutPlan")
                        .WithMany()
                        .HasForeignKey("WorkoutPlanId");

                    b.Navigation("Exercise");

                    b.Navigation("User");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutAnalysis.PerformanceSnapshot", b =>
                {
                    b.HasOne("TrainWise.Core.Domain.Entities.WorkoutComponents.Exercise", "Exercise")
                        .WithMany("PerformanceSnapshots")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainWise.Core.Domain.Entities.UsersComponets.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutAnalysis.ProgressAnalysis", b =>
                {
                    b.HasOne("TrainWise.Core.Domain.Entities.WorkoutComponents.Exercise", "Exercise")
                        .WithMany("ProgressAnalyses")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainWise.Core.Domain.Entities.UsersComponets.User", "User")
                        .WithMany("ProgressAnalyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutAnalysis.VolumeAnalysis", b =>
                {
                    b.HasOne("TrainWise.Core.Domain.Entities.UsersComponets.User", "User")
                        .WithMany("VolumeAnalyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutComponents.SetExecution", b =>
                {
                    b.HasOne("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutSession", "WorkoutSession")
                        .WithMany("SetExecutions")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutTemplateExercise", "WorkoutTemplateExercise")
                        .WithMany("SetExecutions")
                        .HasForeignKey("WorkoutTemplateExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkoutSession");

                    b.Navigation("WorkoutTemplateExercise");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutPlan", b =>
                {
                    b.HasOne("TrainWise.Core.Domain.Entities.UsersComponets.User", "User")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutSession", b =>
                {
                    b.HasOne("TrainWise.Core.Domain.Entities.UsersComponets.User", "User")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("Sessions")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutTemplate", b =>
                {
                    b.HasOne("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutPlan", "WorkoutPlan")
                        .WithMany("WorkoutTemplates")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutTemplateExercise", b =>
                {
                    b.HasOne("TrainWise.Core.Domain.Entities.WorkoutComponents.Exercise", "Exercise")
                        .WithMany("WorkoutTemplateExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.UsersComponets.User", b =>
                {
                    b.Navigation("AIRecommendations");

                    b.Navigation("Preferences")
                        .IsRequired();

                    b.Navigation("ProgressAnalyses");

                    b.Navigation("VolumeAnalyses");

                    b.Navigation("WorkoutPlans");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutComponents.Exercise", b =>
                {
                    b.Navigation("PerformanceSnapshots");

                    b.Navigation("ProgressAnalyses");

                    b.Navigation("WorkoutTemplateExercises");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutPlan", b =>
                {
                    b.Navigation("WorkoutTemplates");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutSession", b =>
                {
                    b.Navigation("SetExecutions");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutTemplate", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("TrainWise.Core.Domain.Entities.WorkoutComponents.WorkoutTemplateExercise", b =>
                {
                    b.Navigation("SetExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
